version: "3.8"

services:
 mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: MS_SQL_Server
    restart: always
    environment:
      SA_PASSWORD: "Pass123!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql
    ports:
      - 1433:1433
    networks:
          - dev
          
volumes:
  mssql-data:
    # actually this is the default
    driver: local

networks:
  dev:
    # actually this is the default
    driver: bridge
# Address in DatGrip jdbc:sqlserver://localhost\databasename:1433
# "Data Source=localhost,1433;Initial Catalog=theNameOfTheDataBaseHere;User id=sa;Password=Pass123!;MultipleActiveResultSets=True"